# travis-ci.org build & test configuration
language: python
python:
    - "2.7"
    - "3.5"
env:
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda create --yes -n test_env python="$TRAVIS_PYTHON_VERSION" gcc=4.8 numpy nose pip wheel
    - source ~/miniconda/bin/activate test_env
    - export LD_LIBRARY_PATH=~/miniconda/envs/test_env/lib
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.0-py2-none-linux_x86_64.whl;
        else
          pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.0-py3-none-linux_x86_64.whl;
        fi
script: nosetests
cache: apt
notifications:
    email: false
