# travis-ci.org build & test configuration
language: python
python:
    - "3.4"
# 3.5 currently segfaults.
# Enable it with the next tensorflow version
#   - "3.5"
env:
    global:
        secure: OBlwwjHDBgHnGLAtVv22oQORyYu+x2XnRJBW7yA0ZvHkvBErMOyMoftVNGa2tNaP24OeI1bh3s1zQVJ8r1CVADys/DycgD4Asqt69JBLKQtiF7Lap8vKtrQZYmXvbFN1UyvW7nRydy++UBM/o6gyXKeln7AzJz34Feb866SqMideCErI+w2cRwREuoFvemEfJZN/nHii47rkWmVqlm6hdHSMwUfVE0VCEn9HHjXEH5Vp8SeNlMprirSXZr6CrY5JQD0WQlIEz9OjJR63mHMw9RmH2kCL+yKdIy2igJZlhvioGW18MSrGXWLTroUpCR5NIlXgzxQDQQXeStPlfVXHWmEeSQBJt86tFMQwA60+IFhBXuTaQRX9cwHpqqZb4zCJwe4214lvDc2sXH9isbbtk9g3U6eakJCL72c8ci5HpMydodkVB41gv2WwXQgMD4IRTqKjsHGPs8ddzsm/kUP890iSdoAEu+051JQWWtmPXof4Wog37QNt2E04Y2e9R2ykC8u4WrAtObFIC4xDm46ljaBxrVWoSvcyq5dFP2OY2gyxlWLi82BmjTp8rY6Ked3cuOUgmoeMyy+SM1IUi95hk4F2eqZDZu8PMvp6RrrcQY87XXQnFjZdRmDCZBxlj9Elfn/KfUBfBkw2Cj3N6G5/EdnuuPwncQEY/jpSf9qAQwE=
script:
    - echo Done
cache: apt
notifications:
    email: false
